services:
  bot:
    build: .
    container_name: basebot
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: basebot_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:?DB_USER is not specified in .env}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is not specified in .env}
      POSTGRES_DB: ${DB_NAME:?DB_NAME is not specified in .env}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:?DB_USER is not specified in .env} -d ${DB_NAME:?DB_NAME is not specified in .env}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data: